### ISSUE TITLE
Function calls sind teuer

### ISSUE THREAD

**Issue by manpen** [s9770652/pim-sorting#3]
Das erstellen der Zufallszahlen erschien mir überraschend teuer. Rund 52ms für n=1e5. Wenn man 

```static inline T gen_xs1(struct xorshift *rng) { ... }```

Im selben File definiert sinkt die Laufzeit von 52ms auf 33ms ...

**Comment by s9770652** [comment]
Seit 6e6bb8b umgesetzt.
