### ISSUE TITLE
Use sentinels

### ISSUE THREAD

**Issue by manpen** [s9770652/pim-sorting#4]
Wenn wir davon ausgehen, dass wir ein kleinstes Element kennen (für uint32_t ist das 0), können wir InsertionSort deutlich beschleunigen.

Idee: Gehe sicher, dass das Element VOR cache[0] das Minimum hat. Dann können wir uns den (j>0) check in insertion sort schenken. Konkret:

```
static inline void insertion_sort(T *arr, size_t len) {
  for (size_t i = 1; i < len; i++) {

    T *curr = &arr[i];
    T *prev = curr - 1;

    const T to_sort = *curr;

    while (*prev > to_sort) {
      *curr = *prev;
      curr = prev;
      prev--;
    }

    *curr = to_sort;
  }
}
```

Benötigt 200 statt 250ms.

**Comment by s9770652** [comment]
Danke! 45f08f7721523c135cc9b4bffb41cb26465a724c: 6291456ints@16T: 10637 ms → 10381 ms (−2,4 %)
