### ISSUE TITLE
`seqread_tell` ist langsam

### ISSUE THREAD

**Issue by manpen** [s9770652/pim-sorting#6]
Ganz offensichtlich ist `seqread_tell` langsamer, als eigene Counter zu unterhalten. Statt das Ende einer Subsequenz mittels

```c
if (seqread_tell(ptr[active], &sr[active]) == ends[active])
```

zu erkennen, habe ich folgendes gemacht:

```c
size_t elems_left[2] = {run, ends[1] - ends[0]};
while(1) {
   // ...
   if (--elems_left[active] == 0) {
      // ...
   }
   // ...
}
```

Das führt zu einer Beschleunigung von > 20%.

**Comment by s9770652** [comment]
Danke! 7ac7032a362a17ed767053cdf3b6d1c51ca200b9: 6291456ints@16T: 23239 ms → 20416 ms (−12 %)
